teamBlaze/About/urls.py
from django.urls import path
from . import views

app_name = "About"
urlpatterns = [
    path("", views.About, name = 'about_info'),
]

teamBlaze/Home/urls.py
from django.urls import path
from . import views


app_name = "Home"
urlpatterns = [
    path("", views.Home, name = 'Home'),
    path("success/", views.success, name = 'success'),
]

teamBlaze/pssngr_interface/urls.py
from django.urls import path
from . import views

app_name = 'pssngr_interface'

urlpatterns = [
    path('', views.pssngr_view, name = "passenger_view"),
    path('create_need_ride/', views.post_need_ride, name = 'create_need_ride'),
    path('check_need_ride/<int:post_id>/', views.detail_need_ride, name = 'detail_need_ride'),
    path('check_need_ride/', views.check_need_ride, name = 'check_need_ride'),
    path('find_driver/', views.find_driver, name = 'find_driver'),
    path('add_passenger/<int:post_id>/', views.add_passenger, name = 'add_passenger')
]

teamBlaze/rolechoice/urls.py
from django.urls import path
from . import views

app_name = "roleChoice"
urlpatterns = [
    path('', views.rolechoice_view, name = 'roleChoice'),
]

teamBlaze/teamBlaze/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Home/', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', include('About.urls')),
    path('rolechoice/', include('rolechoice.urls')),
    path('', include('Home.urls')),
    path('passenger/', include('pssngr_interface.urls')),
    path('driver/', include('driver_interface.urls')),
    path('test_api/', include('test_api.urls')),
]


urlpatterns += staticfiles_urlpatterns()

teamBlaze/pssngr_interface/models.py
from django.db import models
from driver_interface.models import Post
from accounts.models import MyUser
from django.contrib.auth.models import User

# Create your models here.
class NeedRidePost(Post):
    my_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, default=None)
    driver = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

teamBlaze/pssngr_interface/forms.py
from django import forms

STATE_CHOICE = (("Alabama", "AL"),
                ("Alaska", 'AK'),
                ('Arizona', "AZ"),
                ('Arkansas', 'AR'),
                ('California', 'CA'),
                ('Colorado', 'CO'),
                ('Connecticut', 'CT'),
                ('Delaware', 'DE'),
                ('Florida', 'FL'),
                ('Georgia', 'GA'),
                ('Hawaii', 'HI'),
                ('Idaho', 'ID'),
                ('Illinois', 'IL'),
                ('Indiana', 'IN'),
                ('Iowa', 'IA'),
                ('Kansas', 'KS'),
                ('Kentucky', 'KY'),
                ('Louisiana', 'LA'),
                ('Maine', 'ME'),
                ('Maryland', 'MD'),
                ('Massachusetts', 'MA'),
                ('Michigan', 'MI'),
                ('Minnesota', 'MN'),
                ('Mississippi', 'MS'),
                ('Missouri', 'MO'),
                ('Montana', 'MT'),
                ('Nebraska', 'NE'),
                ('Nevada', 'NV'),
                ('New Hampshire', 'NH'),
                ('New Jersey', 'NJ'),
                ('New Mexico', 'NM'),
                ('New York', 'NY'),
                ('North Carolina', 'NC'),
                ('North Dakota', 'ND'),
                ('Ohio', 'OH'),
                ('Oklahoma', 'OK'),
                ('Oregon', 'OR'),
                ('Pennsylvania', 'PA'),
                ('Rhode Island', 'RI'),
                ('South Carolina', 'SC'),
                ('South Dakota', 'SD'),
                ('Tennessee', 'TN'),
                ('Texas', 'TX'),
                ('Utah', 'UT'),
                ('Vermont', 'VT'),
                ('Virginia', 'VA'),
                ('Washington', 'WA'),
                ('West Virginia', 'WV'),
                ('Wisconsin', 'WI'),
                ('Wyoming', 'WY'),
                ('American Samoa', 'AS'),
                ('District of Columbia', 'DC'),
                ('Federated States of Micronesia', 'FM'),
                ('Guam', 'GU'),
                ('Marshall Islands', 'MH'),
                ('Northern Mariana Islands', 'MP'),
                ('Palau', 'PW'),
                ('Puerto Rico', 'PR'),
                ('Virgin Islands', 'VI'),
)

class createNeedRideForm(forms.Form):
    title = forms.CharField(label="Name of the post")
    seats = forms.IntegerField(label="Number of people need a ride")
    departure_state = forms.CharField(label="State of departure", widget=forms.Select(choices=STATE_CHOICE))
    departure_city = forms.CharField(label="City of departure")
    destination_state = forms.CharField(label="State of destination", widget=forms.Select(choices=STATE_CHOICE))
    destination_city = forms.CharField(label="City of destination")
    price = forms.FloatField(label="Price offer per person")
    bags = forms.IntegerField(label="Number of bags carry")
    date = forms.DateField(widget=forms.SelectDateWidget())
    time = forms.TimeField()

class findDriverForm(forms.Form):
    seats = forms.IntegerField
    departure_state = forms.CharField(label="State of departure", widget=forms.Select(choices=STATE_CHOICE))
    departure_city = forms.CharField(label="City of departure")
    destination_state = forms.CharField(label="State of destination", widget=forms.Select(choices=STATE_CHOICE))
    destination_city = forms.CharField(label="City of destination")
    date = forms.DateField(widget=forms.SelectDateWidget())

class addPassengerForm(forms.Form):
    confirm = forms.CharField(label="Please type CONFIRM here", max_length=10)

teamBlaze/pssngr_interface/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404, HttpResponse
from django.contrib.auth.models import User
from .forms import createNeedRideForm, findDriverForm, addPassengerForm
from .models import NeedRidePost
from driver_interface.models import CarPoolPost
from accounts.models import MyUser

# Create your views here.
def pssngr_view(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            user = User.objects.get(id=user_id)
            my_user = user.myuser
            first_name = my_user.first_name
            context = {'first_name': first_name}
            return render(request, 'pssngr_interface/passenger_options.html', context)
        else:
            return Http404
    except:
        return redirect('Home:Home')

def post_need_ride(request):
    try:
        user_id = request.session['user_id']
    except:
        return redirect('Home:Home')

    if user_id is not None:
        form = createNeedRideForm(request.POST)
        if form.is_valid():
            seats = form.cleaned_data['seats']
            destination_state = form.cleaned_data['destination_state']
            destination_city = form.cleaned_data['destination_city']
            departure_state = form.cleaned_data['departure_state']
            departure_city = form.cleaned_data['departure_city']
            price = form.cleaned_data['price']
            bags = form.cleaned_data['bags']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            title = form.cleaned_data['title']
            user = User.objects.get(id=user_id)
            my_user = user.myuser
            driver = User.objects.get(username = 'test123')
            need_ride_post = NeedRidePost(seats=seats, destination_state=destination_state, destination_city=destination_city,
                                        price=price, bags=bags, date=date, time=time, my_user=my_user, departure_city = departure_city,
                                        departure_state = departure_state, title = title, driver = driver)
            need_ride_post.save()
            return redirect('pssngr_interface:passenger_view')
        return render(request, 'pssngr_interface/create_need_ride.html', {'form':form})
    else:
        return Http404


def check_need_ride(request):
    try:
        user_id = request.session['user_id']
    except:
        return redirect('Home:Home')

    if user_id is not None:
        user = User.objects.get(id= user_id)
        my_user = user.myuser
        #need_ride_posts = my_user.need_ride_post_set.all()
        need_ride_posts = NeedRidePost.objects.all()
        posts = []
        for post in need_ride_posts:
            if post.my_user.pk == my_user.pk:
                posts.append(post)
        return render(request, 'pssngr_interface/check_need_ride.html', {'posts':posts})
    else:
        return redirect('Home:Home')

def detail_need_ride(request, post_id):
    post = get_object_or_404(NeedRidePost, id = post_id)
    return render(request, 'pssngr_interface/detail_need_ride.html', {'post' : post})

def find_driver(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            form = findDriverForm(request.POST)
            if form.is_valid():
                user = User.objects.get(id = user_id)
                my_user = user.myuser
                destination_state = form.cleaned_data['destination_state']
                destination_city = form.cleaned_data['destination_city']
                departure_state = form.cleaned_data['departure_state']
                departure_city = form.cleaned_data['departure_city']
                date = form.cleaned_data['date']
                '''need_ride_posts = NeedRidePost.objects.filter(destination_city = destination_city
                                                              ).filter(destination_state = destination_state
                                                              ).filter(departure_city = departure_city
                                                              ).filter(departure_state = departure_state)
                    #.filter(date = date)'''
                car_pool_posts = CarPoolPost.objects.all()
                posts = []
                for post in car_pool_posts:
                    if post.destination_state == destination_state and post.departure_state == departure_state:
                        if post.departure_city == departure_city and post.destination_city == destination_city:
                            if post.date == date and post.seats > 0:
                                posts.append(post)
                #form.save()
                return render(request, 'pssngr_interface/find_driver.html', {'form' : form,
                                                                             'posts' : posts})
                #return Http404
            else:
                return render(request, 'pssngr_interface/find_driver.html', {'form' : form})
    except:
        return redirect('Home:Home')



def add_passenger(request, post_id):
    try:
        post = CarPoolPost.objects.get(id = post_id)
        user_id = request.session['user_id']
    except:
        return Http404

    if user_id is not None:
        form = addPassengerForm(request.POST)
        user = User.objects.get(id = user_id)
        if form.is_valid():
            confirm = form.cleaned_data['confirm']
            if confirm == 'CONFIRM':
                post.passengers.add(user)
                post.seats -= 1
                post.save()
                return redirect('pssngr_interface:passenger_view')
            else:
                return render(request, 'pssngr_interface/add_passenger.html', {'form' : form,
                                                                               'post' : post})
        else:
            return render(request, 'pssngr_interface/add_passenger.html', {'form': form,
                                                                           'post': post})
    else:
        return Http404

teamBlaze/pssngr_interface/templates/pssngr_interface/add_passenger.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Post's name: {{post.title}}</h1>
    <ul>
      <li>Date : {{post.date}}</li>
      <li>Time : {{post.time}}</li>
      <li>Departure State: {{post.departure_state}}</li>
      <li>Destination State: {{post.destination_state}}</li>
      <li>Destination City : {{post.destination_city}}</li>
      <li>Avaliable Bag Space: {{post.bags}}</li>
      <li>Seats Avaliable :{{post.seats}}</li>
      <li>Price per Seat : {{post.price}}</li>
      <li>Seats Avaliable :{{post.seats}}</li>
    </ul>

    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="CONFIRM">
    </form>

</body>
</html>

teamBlaze/pssngr_interface/templates/pssngr_interface/detail_need_ride.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

<style>
    
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/

    .info-box {
        margin-left: auto;
        margin-right: auto;
        vertical-align: middle;
        width: 50%;   
        background-color: white;
        border-radius: 20px;
        box-shadow: 5px 5px 10px;
        margin-bottom: 20px;
    }
    
    .info-box th {
        text-align: center;
        font-family: "Berlin Sans FB";
        font-weight: 450;
        font-size: 5rem;
    }
    
    .info-box tbody {
        float: left;
        text-align: left;
        margin-left: 270px;
        font-size: 3rem;
        font-weight: bold;
    }
    
.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: "Courier", monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
    
</style>



</head>
<body>


<!--Template starts-->


<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
<div class ="middle">
    <table class ="info-box">
    
    <thead>
    <th style="border-bottom: solid; border-bottom-color: gray;">{{post.title}}</th>
    </thead>
    <tbody>
    <tr>
      <td>Date: {{post.date}}
    <br>
      Time: {{post.time}}
    <br>
      Departure State: {{post.departure_state}}
    <br>
      Departure City: {{post.departure_city}}
    <br>
      Destination State: {{post.destination_state}}
    <br>
      Destination City: {{post.destination_city}}
    <br>
      Requested Bag Space: {{post.bags}}
    <br>
      Requested seats: {{post.seats}}
    <br>
      Offered price per passenger: {{post.price}}
          </td>
    </tr>
    </tbody>
    </table>
    <div class = "someButton">
    <form action="{% url 'pssngr_interface:check_need_ride' %}">
    <button class = "button2">Go back</button>
    </form>
    </div>
</div>
<!--------------------------------YOUR CODE ENDS HERE-------------------------------->

<!--Template starts-->

    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
    </div>

<!--Template ends-->
</div>
</body>
</html>

teamBlaze/pssngr_interface/templates/pssngr_interface/find_driver.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

<style>
    
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/
.main {
    width:1400px;
    margin-left: 350px;    
}

.trip-info {
        width: 500px;
        float: left;
        font-size: 2.5rem;
        font-family: "Berlin Sans FB", "Palatino Linotype", monospace;
        font-weight: 50;
        }

.results {
    width: 800px;
    margin-left: 50px;
    float: left;
    font-size: 2.5rem;
    font-family: "Berlin Sans FB", "Palatino Linotype", monospace;
    font-weight: 50;
    }

.clear {
    clear: both;
    }

    
label {
    display: inline-block;
    float: left;
    text-align: right;
}

input {
    border-radius: 15px;
    display: inline-block;
    float: left;
    width: auto;
}

        
input[type=text]:focus, input[type=password]:focus {
    background-color: aquamarine;
    outline: none;
}
    
    /* Content Table Styling Starts*/
    
    .table-responsive h1 {
        text-align: center;
        font-family: "Berlin Sans FB";
        font-weight: 50;
        font-size: 5rem;
    }
    
    div.table-responsive {
        margin-left: auto;
        margin-right: auto;
        vertical-align: middle;
        width: 100%;
        height: 500px;
        background-color: white;
        border-radius: 20px;
        box-shadow: 5px 5px 10px;
    }
    
    tbody {
        display: block;
        overflow-y: scroll;
        overflow-x: hidden;
    }

    tbody {
    display:block;
    max-height: 320px;
    overflow-y: scroll;
}
    thead, tbody tr {
    display:table;
    width:100%;
}
    
    .table tr {
        font-family: "Palatino Linotype", monospace;
    }
    .table th {
        text-align: center;
    }
    .table-hover tbody tr:hover td {
        background-color: #A8FFFA;
    }
    
    .table {
        counter-reset: rowNumber-1;
    }
    
    .table td a{
        color: red;
        font-weight: bold;
    }
    
    .table td a:hover {
        text-decoration: none;
    }
    
    .table tr {
        counter-increment: rowNumber;
    }
    
    .table tr td:first-child::before {
        content: counter(rowNumber);
    }
    /* Content Table Styling Ends*/
    
.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: #FE5531;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 70px;
    width: 200px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    font-weight: bold;
    color: white;
    
    /*Text*/
    font-family: "Courier", monospace;
    font-size: 2.8rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
    
.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: "Courier", monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
    
</style>


    
</head>
<body>


<!--Template starts-->
    
<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>

    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->



    <div class="main">
    <form class="site-form" method="post">
    {% csrf_token %}
    <div class="trip-info">
    <br>
    <label>Departure State: </label> {{form.departure_state}}
    <br>
    <br>
    <label>Departure City: </label> {{form.departure_city}}
    <br>
    <br>
    <label>Destination State: </label> {{form.destination_state}}
    <br>
    <br>
    <label>Destination City: </label> {{form.destination_city}}
    <br>
    <br>
    <label>Date: </label> {{form.date}}
    <br>
    <br>
    <button class = "button1" type="submit" >Search</button>
    </div>

    </form>
    <div class ="results">
    <div class="table-responsive">
        <h1>Passenger search results</h1>            
        <table class="table table-hover">
            {% csrf_token %}
            <thead>
                <tr>
                    <th style="width:80px">#</th>
                    <th>Post Title</th>
                    <th>Departure State</th>
                    <th>Departure City</th>
                    <th>Destination State</th>
                    <th>Destination City</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td style="width:80px"></td>
                    <td><a href="{% url 'pssngr_interface:add_passenger' post.id %}">{{post.title}}</a></td>
                    <td><a href="{% url 'pssngr_interface:add_passenger' post.id %}">{{post.departure_state}}</a></td>
                    <td><a href="{% url 'pssngr_interface:add_passenger' post.id %}">{{post.departure_city}}</a></td>
                    <td><a href="{% url 'pssngr_interface:add_passenger' post.id %}">{{post.destination_state}}</a></td>
                    <td><a href="{% url 'pssngr_interface:add_passenger' post.id %}">{{post.destination_city}}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
   
    </div>
    <br>
    <div class="clear"></div>
    </div>
    
    <div class = "someButton" style="margin-top:8px">
    <form action="{% url 'pssngr_interface:passenger_view' %}">
    <button class = "button2">Go back</button>
    </form>
    </div>
 

    

<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
    
<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
    </div>
    
<!--Template ends-->
    
</div>
</body>
</html>

teamBlaze/pssngr_interface/templates/pssngr_interface/passenger_options.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">

<style>
    
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/

.middle h {
    position: absolute;
    left: 550px;
    font-family: 'OogieBoogie', "Palatino Linotype", monospace;
    font-size: 6rem;
    font-weight: 300;
    color: hotpink;
    text-shadow: 1px 1px 3px white;
    }

    .button {
        display: inline-block;
        margin-left: 65px;
        margin-right: 65px;
    }
    form1 {
        display: inline-block;
    }

.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: red;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 75px;
    width: 225px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    text-align:center;
    text-decoration: none;
    color: white;
    margin: 0 auto;
    font-family: 'Palatino', 'Palatino Linotype', serif;
    font-size: 30px;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: "Courier", monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
  
</style>

</head>
<body>


<!--Template starts-->

<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>

    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
    <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <h>What would you like to do?</h>
    <br>
    <br>
    <br>
    <br>
    <form style="display: inline;" action="{% url 'pssngr_interface:create_need_ride' %}">
        <button class="button"><span>Ask for ride</span></button>
    </form>
    <form style="display: inline;" action ="{% url 'pssngr_interface:check_need_ride' %}">
        <button class="button"><span>Check trips</span></button>
    </form>
    <form style="display: inline;" action ="{% url 'pssngr_interface:find_driver' %}">
        <button class="button"><span>Find Driver</span></button>
    </form>
    <br>
    <br>
    <br>
    <br>
    <div class = "someButton">
    <form action="{% url 'roleChoice:roleChoice' %}">
    <button class = "button2">Go back</button>
    </form>
    </div>
    </div>
<!--------------------------------YOUR CODE ENDS HERE-------------------------------->

<!--Template starts-->

    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
    </div>

<!--Template ends-->



</div>
</body>
</html>