teamBlaze/About/urls.py
from django.urls import path
from . import views

app_name = "About"
urlpatterns = [
    path("", views.About, name = 'about_info'),
]

teamBlaze/Home/urls.py
from django.urls import path
from . import views


app_name = "Home"
urlpatterns = [
    path("", views.Home, name = 'Home'),
    path("success/", views.success, name = 'success'),
]

teamBlaze/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup_view, name = 'signup'),
    path("login/", views.login_view, name = 'login'),
    path("logout/", views.logout_view, name = 'logout'),
    path("forgot/",views.forgot_view, name = 'forgot'),
    path("userInfo/", views.get_user_info, name = 'userInfo'),
 ]

teamBlaze/teamBlaze/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Home/', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', include('About.urls')),
    path('rolechoice/', include('rolechoice.urls')),
    path('', include('Home.urls')),
    path('passenger/', include('pssngr_interface.urls')),
    path('driver/', include('driver_interface.urls')),
    path('test_api/', include('test_api.urls')),
]


urlpatterns += staticfiles_urlpatterns()

teamBlaze/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class MyUser(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key= True)
    email = models.CharField(max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class Car(models.Model):
    my_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, default=None)
    seats = models.IntegerField()
    year = models.IntegerField()
    model = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)

    def __str__(self):
        return self.my_user.user.username + ' ' + self.model

teamBlaze/accounts/forms.py
from django import forms

class infoForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=100)
    last_name = forms.CharField(label='Last name', max_length=100)
    email = forms.CharField(label='Email', max_length=50)

teamBlaze/accounts/views.py
from django.shortcuts import render, redirect, Http404, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import infoForm
from . models import MyUser
from django.contrib.auth.models import User

def signup_view(request):
    request.session['user_id'] = None
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            user = User.objects.get(username = username)
            request.session['user_id'] = user.id
            return redirect('accounts:userInfo')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form' : form })


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            #log user in
            user = form.get_user()
            login(request,user)
            request.session['user_id'] = user.id
            try:
                my_user = user.myuser
            except:
                return redirect("accounts:userInfo")
            return redirect('../../rolechoice')
    else:
        form = AuthenticationForm()
    return render(request,"accounts/login.html",{'form':form})

def logout_view(request):
    logout(request)
    request.session['user_id'] = None
    return redirect("Home:Home")

def forgot_view(request):
    return render(request,"accounts/forgot.html")

def get_user_info(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            form = infoForm(request.POST)
            if form.is_valid():
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                if user_id is not None:
                    user = User.objects.get(id = user_id)
                    request.session['user_id'] = None
                    my_user = MyUser(email = email, last_name = last_name, first_name = first_name, user = user)
                    my_user.save()
                else:
                    raise Http404
                return redirect('Home:Home')
            return render(request, 'accounts/get_info.html', {'form' : form})
        else:
            return Http404
    except:
        return redirect("Home:Home")

teamBlaze/accounts/templates/accounts/get_info.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

    <style>
        
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/

.middle {
    text-align: center;
    margin: 0;
    font-weight: bold;
    font-family: Courier, monospace;
    font-size: 3rem;
    color: saddlebrown;
    text-shadow: 1px 1px 0px rgba(255, 255, 255, .2);
}


.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: #FE5531;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 70px;
    width: 200px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    font-weight: bold;
    color: white;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-weight: 100;
    font-family: Courier, monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}


label {
    display: inline-block;
    float: left;
    clear: left;
    width: 800px;
    text-align: right;
}

input {
    border-radius: 15px;
    display: inline-block;
    float: left;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: aquamarine;
    outline: none;
}
        
</style>


</head>
<body>

    
    <!--Template starts-->
    
<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
     <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <br>
     <form class="site-form" method="post">
      {% csrf_token %}
    <label>First Name:</label> {{form.first_name}}
    <br>
    <br>
    <label>Last Name:</label> {{form.last_name}}
    <br>
    <br>
    <label>Email:</label> {{form.email}}
    <br>
    <br>
    <button class = "button1" type="submit" >Submit</button>
    </form>
    </div>
<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
    
<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <form action ="{% url 'About:about_info' %}">
        <button class = "buttonn" >About us</button>
        </form>
    </div>
    
<!--Template ends-->
    </div>
</body>
</html>

teamBlaze/accounts/templates/accounts/login.html
<!DOCTYPE html>

<html lang="en">
<head>
  
    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>    
    <script src="js/bootstrap.min.js"></script>
    
    <style>
    
.middle {
    text-align: center;
    margin: 0;
    font-weight: bold;
    font-family: Courier, monospace;
    font-size: 3rem;
    color: saddlebrown;
    text-shadow: 1px 1px 0px rgba(255, 255, 255, .2);
}

.middle p {
    text-align: left;
    margin-left: 860px;
    font-weight: 100;
    font-family: Courier, monospace;
    font-size: 2rem;
    color: black;
    text-decoration: none;
}
        

.button {
    /*Button*/
    border-radius: 25px;
    background-color: #FE5531;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 70px;
    width: 200px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    font-family: Courier, monospace;
    font-weight: bold;
    color: white;
}

.button:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
        
.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    
    /*Text*/
    font-weight: 100;
    font-family: Courier, monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;

}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

input {
    border-radius: 15px;
}

        
input[type=text]:focus, input[type=password]:focus {
    background-color: aquamarine;
    outline: none;
}

    </style>

</head>
<body>
    


    
    <!--Template starts-->
    
<div class="container">
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
   <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <br>
    <br>
    <form class="site-form" method="post">
      {% csrf_token %}
    <label>Username:</label> {{form.username}}
    <br>
    <p><a href ="{% url 'accounts:signup' %}" style="color:brown">Need an account? Join us!</a></p>
    <br>
    <label>Password:</label> {{form.password}}
    <br>
    <p><a href ="{% url 'accounts:forgot' %}" style="color:brown">Forgot your password?</a></p>
    <br>
    <button class = "button" type="submit" >Log in</button>
    <br>
    </form>
    
    <form action="{%url 'Home:Home' %}">
    <button class = "button2" >Go back</button>
    </form>
    </div>    

<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
    
<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <form action ="{% url 'About:about_info' %}">
        <button class = "buttonn" >About us</button>
        </form>
    </div>
    
<!--Template ends-->
</div>
   
    
</body>
</html>

teamBlaze/accounts/templates/accounts/signup.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<style>


.middle {
    text-align: center;
    margin: 0;
    font-weight: bold;
    font-family: Courier, monospace;
    font-size: 3rem;
    color: saddlebrown;
    text-shadow: 1px 1px 0px rgba(255, 255, 255, .2);
}

.middle p1  
    {
        float: left;
        margin-left: 800px;
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 2rem;
        color: red;
    }

.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: #FE5531;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 70px;
    width: 200px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    font-weight: bold;
    color: white;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-weight: 100;
    font-family: Courier, monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}


label {
    display: inline-block;
    float: left;
    clear: left;
    width: 800px;
    text-align: right;
}

input {
    border-radius: 15px;
    display: inline-block;
    float: left;
}


        
input[type=text]:focus, input[type=password]:focus {
    background-color: aquamarine;
    outline: none;
}
        
</style>


</head>
<body>


    
    <!--Template starts-->
    
<div class="container">
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->

     <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <br>
     <form class="site-form" method="post">
      {% csrf_token %}  
    <label>Username:</label> {{form.username}}
    <br>
    <br>
    <label>Password:</label> {{form.password1}}
    <br>
    <p1>Password must contain at least 8 characters <br> and must not be too common.</p1>
    <br>
    <label>Password confirmation:</label> {{form.password2}}
    <br>
    <br>
    <br>
    <button class = "button1" type="submit">Sign up</button>
    </form>
    <br>
    <form action="{%url 'Home:Home' %}">
    <button class = "button2" >Go back</button>
    </form>
    </div>

<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
       
<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <form action ="{% url 'About:about_info' %}">
        <button class = "buttonn" >About us</button>
        </form>
    </div>
    
<!--Template ends-->
    </div>
</body>
</html>

teamBlaze/accounts/templates/accounts/signup1.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

 

</head>
<body>



<div class="container">

    <!--App logo-->
    <div class ="logo">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <p><a href="{%url 'About:about_info' %}"> About us</a></p>
    </div>
<!--Template ends-->

    <!--Account options-->

    <br>
    <br>
    <br>
    
     {% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}
    


</div>

</body>
</html>

teamBlaze/accounts/templates/accounts/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method = "post">
        {% csrf_token %}
        {{form.as_p}}
    </form>
</body>
</html>