teamBlaze/About/urls.py
from django.urls import path
from . import views

app_name = "About"
urlpatterns = [
    path("", views.About, name = 'about_info'),
]

teamBlaze/Home/urls.py
from django.urls import path
from . import views


app_name = "Home"
urlpatterns = [
    path("", views.Home, name = 'Home'),
    path("success/", views.success, name = 'success'),
]

teamBlaze/driver_interface/urls.py
from django.urls import path
from . import views

app_name = 'driver_interface'
urlpatterns = [
    path('', views.driver_view, name = 'driver_view'),
    path('create_car/', views.create_car, name = 'create_car'),
    path('create_car_pool/', views.post_car_pool, name = 'create_car_pool'),
    path('check_car_pool/<int:post_id>/', views.detail_car_pool, name = 'detail_car_pool'),
    path('check_car_pool/', views.check_car_pool, name = 'check_car_pool'),
    path('find_passenger/', views.find_passenger, name = 'find_passenger'),
    path('add_driver/<int:post_id>/', views.add_driver, name = 'add_driver'),
    path('compare_price/', views.compare_price, name = 'compare_price'),
]

teamBlaze/rolechoice/urls.py
from django.urls import path
from . import views

app_name = "roleChoice"
urlpatterns = [
    path('', views.rolechoice_view, name = 'roleChoice'),
]

teamBlaze/teamBlaze/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Home/', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', include('About.urls')),
    path('rolechoice/', include('rolechoice.urls')),
    path('', include('Home.urls')),
    path('passenger/', include('pssngr_interface.urls')),
    path('driver/', include('driver_interface.urls')),
    path('test_api/', include('test_api.urls')),
]


urlpatterns += staticfiles_urlpatterns()

teamBlaze/driver_interface/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import *

# Create your models here.
STATE_CHOICE = (("Alabama", "AL"),
                ("Alaska", 'AK'),
                ('Arizona', "AZ"),
                ('Arkansas', 'AR'),
                ('California', 'CA'),
                ('Colorado', 'CO'),
                ('Connecticut', 'CT'),
                ('Delaware', 'DE'),
                ('Florida', 'FL'),
                ('Georgia', 'GA'),
                ('Hawaii', 'HI'),
                ('Idaho', 'ID'),
                ('Illinois', 'IL'),
                ('Indiana', 'IN'),
                ('Iowa', 'IA'),
                ('Kansas', 'KS'),
                ('Kentucky', 'KY'),
                ('Louisiana', 'LA'),
                ('Maine', 'ME'),
                ('Maryland', 'MD'),
                ('Massachusetts', 'MA'),
                ('Michigan', 'MI'),
                ('Minnesota', 'MN'),
                ('Mississippi', 'MS'),
                ('Missouri', 'MO'),
                ('Montana', 'MT'),
                ('Nebraska', 'NE'),
                ('Nevada', 'NV'),
                ('New Hampshire', 'NH'),
                ('New Jersey', 'NJ'),
                ('New Mexico', 'NM'),
                ('New York', 'NY'),
                ('North Carolina', 'NC'),
                ('North Dakota', 'ND'),
                ('Ohio', 'OH'),
                ('Oklahoma', 'OK'),
                ('Oregon', 'OR'),
                ('Pennsylvania', 'PA'),
                ('Rhode Island', 'RI'),
                ('South Carolina', 'SC'),
                ('South Dakota', 'SD'),
                ('Tennessee', 'TN'),
                ('Texas', 'TX'),
                ('Utah', 'UT'),
                ('Vermont', 'VT'),
                ('Virginia', 'VA'),
                ('Washington', 'WA'),
                ('West Virginia', 'WV'),
                ('Wisconsin', 'WI'),
                ('Wyoming', 'WY'),
                ('American Samoa', 'AS'),
                ('District of Columbia', 'DC'),
                ('Federated States of Micronesia', 'FM'),
                ('Guam', 'GU'),
                ('Marshall Islands', 'MH'),
                ('Northern Mariana Islands', 'MP'),
                ('Palau', 'PW'),
                ('Puerto Rico', 'PR'),
                ('Virgin Islands', 'VI'),
)

class Post(models.Model):
    title = models.CharField(max_length=100, default="")
    seats = models.IntegerField()

    destination_state = models.CharField(max_length=100, choices=STATE_CHOICE)
    destination_city = models.CharField(max_length=100)
    departure_state = models.CharField(max_length=100, choices=STATE_CHOICE)
    departure_city = models.CharField(max_length=100)
    price = models.FloatField()
    bags = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()

class CarPoolPost(Post):
    my_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, default=None)
    passengers = models.ManyToManyField(User)

teamBlaze/driver_interface/forms.py
from django import forms

class carForm(forms.Form):
    seats = forms.IntegerField(label="Number of seats")
    year = forms.IntegerField(label="Year that your car is manufactured")
    model = forms.CharField(label="Model of the car", max_length=100)
    manufacturer = forms.CharField(label="Manufacturer of the car", max_length=100)

STATE_CHOICE = (("Alabama", "AL"),
                ("Alaska", 'AK'),
                ('Arizona', "AZ"),
                ('Arkansas', 'AR'),
                ('California', 'CA'),
                ('Colorado', 'CO'),
                ('Connecticut', 'CT'),
                ('Delaware', 'DE'),
                ('Florida', 'FL'),
                ('Georgia', 'GA'),
                ('Hawaii', 'HI'),
                ('Idaho', 'ID'),
                ('Illinois', 'IL'),
                ('Indiana', 'IN'),
                ('Iowa', 'IA'),
                ('Kansas', 'KS'),
                ('Kentucky', 'KY'),
                ('Louisiana', 'LA'),
                ('Maine', 'ME'),
                ('Maryland', 'MD'),
                ('Massachusetts', 'MA'),
                ('Michigan', 'MI'),
                ('Minnesota', 'MN'),
                ('Mississippi', 'MS'),
                ('Missouri', 'MO'),
                ('Montana', 'MT'),
                ('Nebraska', 'NE'),
                ('Nevada', 'NV'),
                ('New Hampshire', 'NH'),
                ('New Jersey', 'NJ'),
                ('New Mexico', 'NM'),
                ('New York', 'NY'),
                ('North Carolina', 'NC'),
                ('North Dakota', 'ND'),
                ('Ohio', 'OH'),
                ('Oklahoma', 'OK'),
                ('Oregon', 'OR'),
                ('Pennsylvania', 'PA'),
                ('Rhode Island', 'RI'),
                ('South Carolina', 'SC'),
                ('South Dakota', 'SD'),
                ('Tennessee', 'TN'),
                ('Texas', 'TX'),
                ('Utah', 'UT'),
                ('Vermont', 'VT'),
                ('Virginia', 'VA'),
                ('Washington', 'WA'),
                ('West Virginia', 'WV'),
                ('Wisconsin', 'WI'),
                ('Wyoming', 'WY'),
                ('American Samoa', 'AS'),
                ('District of Columbia', 'DC'),
                ('Federated States of Micronesia', 'FM'),
                ('Guam', 'GU'),
                ('Marshall Islands', 'MH'),
                ('Northern Mariana Islands', 'MP'),
                ('Palau', 'PW'),
                ('Puerto Rico', 'PR'),
                ('Virgin Islands', 'VI'),
)

class createCarPoolForm(forms.Form):
    title = forms.CharField(label="Name of the post")
    seats = forms.IntegerField(label="Number of seats available")
    departure_state = forms.CharField(label="State of departure", widget=forms.Select(choices=STATE_CHOICE))
    departure_city = forms.CharField(label="City of departure")
    destination_state = forms.CharField(label="State of destination", widget=forms.Select(choices=STATE_CHOICE))
    destination_city = forms.CharField(label="City of destination")
    bags = forms.IntegerField(label="Number of bags carry")
    date = forms.DateField(widget=forms.SelectDateWidget())
    time = forms.TimeField()

class findPassengerForm(forms.Form):
    departure_state = forms.CharField(label="State of departure", widget=forms.Select(choices=STATE_CHOICE))
    departure_city = forms.CharField(label="City of departure")
    destination_state = forms.CharField(label="State of destination", widget=forms.Select(choices=STATE_CHOICE))
    destination_city = forms.CharField(label="City of destination")
    date = forms.DateField(widget=forms.SelectDateWidget())

class getPriceForm(forms.Form):
    price = forms.FloatField(label="Price")

class addDriverForm(forms.Form):
    confirm = forms.CharField(label="Please type CONFIRM here", max_length=10)

teamBlaze/driver_interface/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404, HttpResponse
from django.contrib.auth.models import User
from .forms import createCarPoolForm, carForm, findPassengerForm, addDriverForm, getPriceForm
from .models import CarPoolPost, Car
from pssngr_interface.models import NeedRidePost
import test_api.views as apis

# Create your views here.

def driver_view(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            user = User.objects.get(id = user_id)
            my_user = user.myuser
            first_name = my_user.first_name
            context = {'first_name' : first_name}
            return render(request, 'driver_interface/driver_options.html', context)
        else:
            return Http404
    except:
        return redirect("Home:Home")

def compare_price(request):
    try:
        user_id = request.session['user_id']
    except:
        return redirect("Home:Home")

    try:
        post_id = request.session['post_id']
    except:
        return Http404

    if user_id is not None and post_id is not None:
        post = get_object_or_404(CarPoolPost, id = post_id)
        source = post.departure_city + " " + post.departure_state
        destination = post.destination_city + " " + post.destination_state
        uber_price = apis.get_uber_price(source, destination)
        form = getPriceForm(request.POST)
        if form.is_valid():
            price = form.cleaned_data['price']
            post.price = price
            post.save()
            request.session['post_id'] = None
            return redirect("driver_interface:driver_view")
        else:
            return render(request, 'driver_interface/compare_price.html', {"form": form,
                                                                           'uber_price': uber_price})
    else:
        return redirect("Home:Home")


def post_car_pool(request):
    try:
        user_id = request.session['user_id']
    except:
        return redirect("Home:Home")

    if user_id is not None:
        form = createCarPoolForm(request.POST)
        if form.is_valid():
            seats = form.cleaned_data['seats']
            destination_state = form.cleaned_data['destination_state']
            destination_city = form.cleaned_data['destination_city']
            departure_state = form.cleaned_data['departure_state']
            departure_city = form.cleaned_data['departure_city']
            bags = form.cleaned_data['bags']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            title = form.cleaned_data['title']
            user = User.objects.get(id=user_id)
            my_user = user.myuser
            car_pool_post = CarPoolPost(seats=seats, destination_state=destination_state,
                                        destination_city=destination_city, price = 0,
                                        bags=bags, date=date, time=time, my_user=my_user, departure_city=departure_city,
                                        departure_state=departure_state, title=title)
            car_pool_post.save()
            request.session['post_id'] = car_pool_post.id
            return redirect('driver_interface:compare_price')
        return render(request, 'driver_interface/create_car_pool.html', {'form': form})
    else:
        return Http404

def create_car(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            form = carForm(request.POST)
            if form.is_valid():
                seats = form.cleaned_data['seats']
                year = form.cleaned_data['year']
                model = form.cleaned_data['model']
                manufacturer = form.cleaned_data['manufacturer']
                my_user = (User.objects.get(id = user_id)).myuser

                car = Car(seats = seats, year = year, model = model, manufacturer = manufacturer, my_user = my_user)
                car.save()
                return redirect('driver_interface:driver_view')
            return render(request, 'driver_interface/create_car.html', {'form': form})
        else:
            return Http404
    except:
        return redirect("Home:Home")

def check_car_pool(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            user = User.objects.get(id= user_id)
            my_user = user.myuser
            car_pool_posts = my_user.carpoolpost_set.all()
            return render(request, 'driver_interface/check_car_pool.html', {'car_pool_posts':car_pool_posts})
        else:
            return Http404
    except:
        return redirect('Home:Home')

def detail_car_pool(request, post_id):
    post = get_object_or_404(CarPoolPost, id = post_id)
    return render(request, 'driver_interface/detail_car_pool.html', {'post' : post})

def find_passenger(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            form = findPassengerForm(request.POST)
            if form.is_valid():
                user = User.objects.get(id = user_id)
                my_user = user.myuser
                destination_state = form.cleaned_data['destination_state']
                destination_city = form.cleaned_data['destination_city']
                departure_state = form.cleaned_data['departure_state']
                departure_city = form.cleaned_data['departure_city']
                date = form.cleaned_data['date']
                '''need_ride_posts = NeedRidePost.objects.filter(destination_city = destination_city
                                                              ).filter(destination_state = destination_state
                                                              ).filter(departure_city = departure_city
                                                              ).filter(departure_state = departure_state)
                    #.filter(date = date)'''
                need_ride_posts = NeedRidePost.objects.all()
                posts = []
                for post in need_ride_posts:
                    if post.destination_state == destination_state and post.departure_state == departure_state:
                        if post.departure_city == departure_city and post.destination_city == destination_city:
                            if post.date == date and post.driver.username == 'test123':
                                posts.append(post)
                #form.save()
                return render(request, 'driver_interface/find_passenger.html', {'form' : form,
                                                                                'posts' : posts})
                #return Http404
            else:
                return render(request, 'driver_interface/find_passenger.html', {'form' : form})
    except:
        return redirect('Home:Home')

def add_driver(request, post_id):
    try:
        post = NeedRidePost.objects.get(id = post_id)
        user_id = request.session['user_id']
    except:
        return Http404

    if user_id is not None:
        form = addDriverForm(request.POST)
        user = User.objects.get(id = user_id)
        if form.is_valid():
            confirm = form.cleaned_data['confirm']
            if confirm == 'CONFIRM':
                post.driver = user
                post.save()
                return redirect('driver_interface:driver_view')
            else:
                return render(request, 'driver_interface/add_driver.html', {'form': form,
                                                                            'post': post})
        else:
            return render(request, 'driver_interface/add_driver.html', {'form' : form,
                                                                        'post' : post})
    else:
        return Http404

teamBlaze/driver_interface/templates/driver_interface/add_driver.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Post's name: {{post.title}}</h1>
    <ul>
        <li>Date : {{post.date}}</li>
        <li>Time : {{post.time}}</li>
        <li>Departure State: {{post.departure_state}}</li>
        <li>Destination State: {{post.destination_state}}</li>
        <li>Destination City : {{post.destination_city}}</li>
        <li>Avaliable Bag Space: {{post.bags}}</li>
        <li>Seats Avaliable :{{post.seats}}</li>
        <li>Price per Seat : {{post.price}}</li>
        <li>Seats Avaliable :{{post.seats}}</li>
        <li>ID :{{post.id}}</li>
    </ul>


    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="JOIN">
    </form>



</body>
</html>

<!--
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">

<style>


</head>
<body>


<!--Template starts--

<div class="container">

    <!--App logo--
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

<!--Template ends-->

<!--------------------------------YOURs CODE STARTS HERE-------------------------------->



<!--------------------------------YOUR CODE ENDS HERE-------------------------------->

<!--Template starts-->

    <!--About section--
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <form action ="{% url 'About:about_info' %}">
        <button class = "buttonn" >About us</button>
        </form>
    </div>

<!--Template ends-->

teamBlaze/driver_interface/templates/driver_interface/compare_price.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
<style>
    
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/

.middle h {
    text-align: center;
    font-size: 5rem;
    color: crimson;
    font-weight: 50;
    font-family: "Berlin Sans FB", "Palatino Linotype", monospace;
    text-shadow: 2px 5px 10px rgba(109, 87, 25, .3);
}
    
.uber-price {
    font-size: 10rem;
    color: #FFCA33;
    text-shadow: 2px 5px 10px rgba(109, 87, 25);
}

    
label {
    display: inline-block;
    float: left;
    margin-left: 700px;
    color: mediumvioletred;
    font-size: 4rem;
    font-weight: 50;
    font-family: "Berlin Sans FB", "Palatino Linotype", monospace;
    text-shadow: 2px 5px 10px rgba(0, 0, 0, .4);
}

input {
    border-radius: 15px;
    display: inline-block;
    margin-left: 5px;
    float: left;
    width: auto;
}

        
input[type=text]:focus, input[type=password]:focus {
    background-color: aquamarine;
    outline: none;
}

.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: #FE5531;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 70px;
    width: 200px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);
    font-weight: bold;
    color: white;
    
    /*Text*/
    font-family: "Courier", monospace;
    font-size: 2.8rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: "Courier", monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
    
.button3 span {
    cursor: pointer;
    display: inline-block;
    position: relative;
    transition: 0.5s;
}

.button3 {
    /*Button*/
    border-radius: 20px;
    background-color: slateblue;
    display: inline-block;
    margin-left: 10px;
    height: 50px;
    width: 130px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: Courier, monospace;
    font-size: 1.7rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}
    
.button3 span:after {
    content: '\00bb';
    position: absolute;
    opacity: 0;
    top: 0;
    right: -20px;
    transition: 0.5s;
}

.button3:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button3:hover span {
    padding-right: 25px;
}

.button3:hover span:after {
    opacity: 1;
    right: 0;
}
</style>
    
</head>
<body>
    

<!--Template starts-->
    
<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
    <div class="middle">
    <h>Uber's price for a similar ride: <div class="uber-price">{{uber_price}}</div></h>

    <br>
    <form method="post">
        {% csrf_token %}
    <label>Your desired price: </label> {{form.price}}
    <br>
    <br>

        
    <div class = "someButton">
    <button class = "button1" type="submit" >Submit</button>
    </div> 
    </form>
    <br>
    <div class = "someButton">
    <form action="{% url 'driver_interface:create_car_pool' %}">
    <button class = "button2">Go back</button>
    </form>
        
    </div>
    </div>
<!--------------------------------YOUR CODE ENDS HERE-------------------------------->

<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
    </div>
    
<!--Template ends-->

</div>
</body>
</html>

teamBlaze/driver_interface/templates/driver_interface/create_car.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>You are creating a car</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
    <form method="POST" action="/logout/">
      {% csrf_token%}
      <input type="Submit" value="logout">
    </form>

</body>
</html>

teamBlaze/driver_interface/templates/driver_interface/driver_options.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">

<style>
    
/*Testing Navigation bar starts here*/

.topnav {
  overflow: auto;
  background-color: (153, 217, 234);
}

.topnav a {
  position: relative;
  float: left;
  padding: 14px 16px;
    
  color: #f2f2f2;
  text-align: center;
  text-decoration: none;
  font-family: "Berlin Sans FB", monospace;
  font-size: 2rem;
  font-weight: 100;
  border-radius: 20px;
}

.topnav a:hover {
  background-color: slateblue;
  color: white;
}


/*Testing Navigation bar ends here*/

.middle h {
    position: absolute;
    left: 550px;
    font-family: 'OogieBoogie', "Palatino Linotype", monospace;
    font-size: 6rem;
    font-weight: 300;
    color: hotpink;
    text-shadow: 1px 1px 3px white;
    }

    .button {
        display: inline-block;
        margin-left: 65px;
        margin-right: 65px;
    }
    form1 {
        display: inline-block;
    }

.button1 {
    /*Button*/
    border-radius: 25px;
    background-color: red;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 75px;
    width: 225px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    text-align:center;
    text-decoration: none;
    color: white;
    margin: 0 auto;
    font-family: 'Palatino', 'Palatino Linotype', serif;
    font-size: 30px;
}

.button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

.button2 {
    /*Button*/
    border-radius: 20px;
    background-color: #31CFFE;
    padding: 15px 32px;
    vertical-align: middle;
    display: block;
    margin-left: auto;
    margin-right: auto;
    height: 50px;
    width: 150px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
    box-shadow: 0 5px 10px 0 rgba(0,0,0,0.24),0 12px 30px 0 rgba(0,0,0,0.19);

    /*Text*/
    font-family: "Courier", monospace;
    font-size: 1.5rem;
    font-weight: bold;
    text-decoration: none;
    color: white;
}

.button2:hover {;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
  
</style>

</head>
<body>


<!--Template starts-->

<div class="container">
    
    <div class="topnav">
        <a href="{% url 'Home:Home' %}">Home</a>
        <a href="{% url 'About:about_info' %}">About</a>
        <a href="">Feedback</a>
        <a href="/accounts/logout/">Log out</a>
    </div>

    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
    <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <h>What would you like to do?</h>
    <br>
    <br>
    <br>
    <br>
    <form style="display: inline;" action="{% url 'driver_interface:create_car_pool' %}">
        <button class="button"><span>Post Car Pool</span></button>
    </form>
    <form style="display: inline;" action ="{% url 'driver_interface:check_car_pool' %}">
        <button class="button"><span>Check Carpool</span></button>
    </form>
    <form style="display: inline;" action ="{% url 'driver_interface:find_passenger' %}">
        <button class="button"><span>Find Passenger</span></button>
    </form>
    <br>
    <br>
    <br>
    <br>
    <div class = "someButton">
    <form action="{% url 'roleChoice:roleChoice' %}">
    <button class = "button2">Go back</button>
    </form>
    </div>
    </div>
<!--------------------------------YOUR CODE ENDS HERE-------------------------------->

<!--Template starts-->

    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
    </div>

<!--Template ends-->



</div>
</body>
</html>