teamBlaze/About/urls.py
from django.urls import path
from . import views

app_name = "About"
urlpatterns = [
    path("", views.About, name = 'about_info'),
]

teamBlaze/Home/urls.py
from django.urls import path
from . import views


app_name = "Home"
urlpatterns = [
    path("", views.Home, name = 'Home'),
    path("success/", views.success, name = 'success'),
]

teamBlaze/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup_view, name = 'signup'),
    path("login/", views.login_view, name = 'login'),
    path("logout/", views.logout_view, name = 'logout'),
    path("forgot/",views.forgot_view, name = 'forgot'),
    path("userInfo/", views.get_user_info, name = 'userInfo'),
 ]

teamBlaze/teamBlaze/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Home/', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', include('About.urls')),
    path('rolechoice/', include('rolechoice.urls')),
    path('', include('Home.urls')),
    path('passenger/', include('pssngr_interface.urls')),
    path('driver/', include('driver_interface.urls')),
    path('test_api/', include('test_api.urls')),
]


urlpatterns += staticfiles_urlpatterns()

teamBlaze/Home/views.py
from django.shortcuts import render, redirect

def Home(request):
    try:
        user_id = request.session['user_id']
        if user_id is not None:
            return redirect('roleChoice:roleChoice')
        else:
            return render(request, 'Home/homepage.html')
    except:
        return render(request, 'Home/homepage.html')

def success(request):
    return render(request, 'Home/success.html')

'''def Feedback_view(request):
    form = Feedback_Form(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(request)
    context = {'form': form}
    return render(request, 'Home/feedback.html', context )'''

teamBlaze/Home/templates/Home/feedback.html
<!DOCTYPE html>
<html>

<form method = 'POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type ='submit' value="Save"/>
</form>



</html>

teamBlaze/Home/templates/Home/homepage.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>


</head>
<body>


<!--Template starts-->
    
<div class="container">
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
    <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <br>
    <form action="{% url 'accounts:login' %}">
    <button class ="button"><span>Log in</span></button>
    </form>
    <br>
    <br>
    <br>
    <form action="{% url 'accounts:signup' %}">
    <button class="button"><span>Sign up</span></button>
    </form>
    </div>

<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
    
<!--Template starts-->
    
    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
        <form action ="{% url 'About:about_info' %}">
        <button class = "buttonn" >About us</button>
        </form>
    </div>
    
<!--Template ends-->


    
</div>

</body>
</html>

teamBlaze/Home/templates/Home/homepage1.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>


</head>
<body>


<!--Template starts-->

<div class="container">

    <!--App logo-->
    <div class ="logo">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>

    <!--About section-->
    <div class="about">
    <h1>&copy; Team Blaze&trade; </h1>
         <p><a href="some_stuff">About Us</a></p>
    </div>
<!--Template ends-->

    <!--Account options-->
    <div class ="middle">

    <a href="{% url 'accounts:login' %}">
    <button class ="button button1"><span>Log in</span></button>
    </a>

    <a href="{% url 'accounts:signup' %}">
    <button class="button button2"><span>Sign up</span></button>
    </a>
    </div>

</div>


</body>
</html>

teamBlaze/Home/templates/Home/success.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <title>TRYP</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-theme.css">
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>


</head>
<body>

<style>
    
.middle h {
    position: absolute;
    left: 550px;
    font-family: 'OogieBoogie', "Palatino Linotype", monospace;
    font-size: 20rem;
    font-weight: 300;
    color: hotpink;
    text-shadow: 1px 1px 3px white;
    }    
    
</style>

<!--Template starts-->
    
<div class="container">
    
    <!--App logo-->
    <div class ="logo">
        <img src="/static/transBG.png">
        <h1>T.R.Y.P</h1>
        <p>Are you tryppin'? </p>
    </div>
    
<!--Template ends-->

<!--------------------------------YOUR CODE STARTS HERE-------------------------------->
    <!--Account options-->
    <div class ="middle">
    <br>
    <br>
    <br>
    <br>
        <h>Successful!</h>
    </div>

<!--------------------------------YOUR CODE ENDS HERE-------------------------------->
    
<!--Template starts-->
    
    <!--About section-->
    
<!--Template ends-->


    
</div>

</body>
</html>